// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close():Promise<void>;

export function SetFocusing(arg1:boolean):Promise<void>;

export function SetOnFocusSet(arg1:any):Promise<void>;
