// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close():Promise<void>;

export function Connect():Promise<void>;

export function Disconnect():Promise<void>;

export function FocusNow():Promise<void>;

export function GetFocusing():Promise<boolean>;

export function SetFocusing(arg1:boolean):Promise<void>;
