// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['coach']['Coach']['Close']();
}

export function SetFocusing(arg1) {
  return window['go']['coach']['Coach']['SetFocusing'](arg1);
}

export function SetOnFocusSet(arg1) {
  return window['go']['coach']['Coach']['SetOnFocusSet'](arg1);
}
