// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['coach']['Coach']['Close']();
}

export function Connect() {
  return window['go']['coach']['Coach']['Connect']();
}

export function Disconnect() {
  return window['go']['coach']['Coach']['Disconnect']();
}

export function FocusNow() {
  return window['go']['coach']['Coach']['FocusNow']();
}

export function GetFocusing() {
  return window['go']['coach']['Coach']['GetFocusing']();
}

export function SetFocusing(arg1) {
  return window['go']['coach']['Coach']['SetFocusing'](arg1);
}
