// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {pomodoro} from '../models';

export function GetButtons():Promise<Array<pomodoro.ButtonInfo>>;

export function GetTimeLeft():Promise<string>;

export function Pause():Promise<void>;

export function Resume():Promise<void>;

export function Start():Promise<void>;

export function Stop():Promise<void>;
