// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetButtons() {
  return window['go']['pomodoro']['Pomo']['GetButtons']();
}

export function GetTimeLeft() {
  return window['go']['pomodoro']['Pomo']['GetTimeLeft']();
}

export function Pause() {
  return window['go']['pomodoro']['Pomo']['Pause']();
}

export function Resume() {
  return window['go']['pomodoro']['Pomo']['Resume']();
}

export function Start() {
  return window['go']['pomodoro']['Pomo']['Start']();
}

export function Stop() {
  return window['go']['pomodoro']['Pomo']['Stop']();
}
