// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPomodoroButtons() {
  return window['go']['main']['App']['GetPomodoroButtons']();
}

export function GetPomodoroState() {
  return window['go']['main']['App']['GetPomodoroState']();
}

export function GetTimeLeft() {
  return window['go']['main']['App']['GetTimeLeft']();
}

export function PausePomodoro() {
  return window['go']['main']['App']['PausePomodoro']();
}

export function ResumePomodoro() {
  return window['go']['main']['App']['ResumePomodoro']();
}

export function SetPomodoroTime(arg1) {
  return window['go']['main']['App']['SetPomodoroTime'](arg1);
}

export function StartPomodoro() {
  return window['go']['main']['App']['StartPomodoro']();
}

export function StopPomodoro() {
  return window['go']['main']['App']['StopPomodoro']();
}
