// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetPomodoroButtons():Promise<Array<main.ButtonInfo>>;

export function GetPomodoroState():Promise<main.PomodoroState>;

export function GetTimeLeft():Promise<number>;

export function PausePomodoro():Promise<void>;

export function ResumePomodoro():Promise<void>;

export function SetPomodoroTime(arg1:number):Promise<void>;

export function StartPomodoro():Promise<void>;

export function StopPomodoro():Promise<void>;
