// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect() {
  return window['go']['main']['WebSocketHandler']['Connect']();
}

export function Disconnect() {
  return window['go']['main']['WebSocketHandler']['Disconnect']();
}

export function GetFocus() {
  return window['go']['main']['WebSocketHandler']['GetFocus']();
}
